" DO NOT EDIT THIS FILE
" Add your own customizations in ~/.dotfiles/config/nvim/vimrc/my_configs.vim

set runtimepath+=~/.dotfiles/config/nvim/vimrc

source ~/.dotfiles/config/nvim/vimrc/vimrcs/basic.vim
source ~/.dotfiles/config/nvim/vimrc/vimrcs/filetypes.vim
source ~/.dotfiles/config/nvim/vimrc/vimrcs/plugins_config.vim
source ~/.dotfiles/config/nvim/vimrc/vimrcs/extended.vim
try
  source ~/.dotfiles/config/nvim/vimrc/my_configs.vim
catch
endtry

call plug#begin()
Plug 'neovim/nvim-lspconfig'
Plug 'vimwiki/vimwiki'

call plug#end()
