" DO NOT EDIT THIS FILE
" Add your own customizations in /Users/johansson044/.dotfiles/config/nvim/vimrc/my_configs.vim

set runtimepath+=/Users/johansson044/.dotfiles/config/nvim/vimrc

source /Users/johansson044/.dotfiles/config/nvim/vimrc/vimrcs/basic.vim
source /Users/johansson044/.dotfiles/config/nvim/vimrc/vimrcs/filetypes.vim
source /Users/johansson044/.dotfiles/config/nvim/vimrc/vimrcs/plugins_config.vim
source /Users/johansson044/.dotfiles/config/nvim/vimrc/vimrcs/extended.vim
try
  source /Users/johansson044/.dotfiles/config/nvim/vimrc/my_configs.vim
catch
endtry

"Plugins
call plug#begin('~/.vim/plugged')
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'

Plug 'neovim/nvim-lspconfig'

call plug#end()


"LSP
lua << EOF
require'lspconfig'.tsserver.setup{}
EOF

